### ISSUE TITLE
Missing indentation

### ISSUE THREAD

**Issue by JonasGroeger** [ubuntudesign/snapcraft.io#45]
http://snapcraft.io/create/

```
parts:
foo-stable:
    plugin: autotools
    source: http://releases.foo.org/download/foo-stable.tar.gz
```

change to

```
parts:
  foo-stable:
      plugin: autotools
      source: http://releases.foo.org/download/foo-stable.tar.gz
```
